export { default as Header } from './header/header'
export { default as Recruiter } from './homepage/recruiter'
export { default as Footer } from './footer/footer'
export { default as Jobseeker } from './homepage/jobseeker'
export { default as Login } from './jobseeker/Login'
export { default as Signup } from './jobseeker/Signup'
export { default as ProtectedRoute } from './jobseeker/ProtectedRoute'
export { default as Home } from './dashboard/Home'
export { default as Loginrec } from './recruiter/Loginrec'
export { default as Signuprec } from './recruiter/Signuprec'
export { default as ProtectedRouterec } from './recruiter/ProtectedRouterec'
export { default as Homerec } from './dashboard/Homerec'
export { default as Privacy } from './footer/privacy'
export { default as Downloadpage } from './downloadpage/downloadpage'
export { default as Contact } from './contact/contact'
export { default as Blogjob } from './blog/blogjob'
export { default as Blogrec } from './blog/blogrec'
export { default as Jobpost } from './Job/jobpost'
export { default as Jobdetails } from './Job/jobdetails'
export { default as Chats } from './chat/chats'
export { default as Companydetails } from './company/companydetails'
export { default as ShowProfile } from './jobseeker/ShowProfile'
export { default as ShowProfileRec } from './recruiter/ShowProfilerec'
export { default as EditProfile } from './jobseeker/EditPage'
export { default as EditProfileRec } from './recruiter/EditProfilerec'
export { default as AddJob} from './addjobrec/addjobrec'
export { default as Headerjob} from './header/headerjob'
export { default as Headerrec} from './header/headerrec'
export {default as Deletejob} from './deletejob/deletejob'